server:
  port: 8086

spring:
  application:
    name: chatbot-proxy-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

chatbot:
  server:
    url: http://chatbot-service:8000